### ISSUE TITLE
AWS Lambda / Cache + read-only Filesystem

### ISSUE THREAD

**Issue by rmcs2002** [Doist/todoist-python#25]
I was trying to run this on AWS Lambda but it fails since it tries to read/write the cache from the user's home folder?

```
[Errno 30] Read-only file system: '/home/sbx_user1083': OSError
Traceback (most recent call last):
File "/var/task/vimeo_settings.py", line 113, in lambda_handler
api = todoist.TodoistAPI()
File "/var/task/todoist/api.py", line 90, in __init__
self._read_cache()
File "/var/task/todoist/api.py", line 197, in _read_cache
os.makedirs(self.cache)
File "/usr/lib64/python2.7/os.py", line 150, in makedirs
makedirs(head, mode)
File "/usr/lib64/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/home/sbx_user1083'
```

Would it be possible to change this? In AWS Lambda, only the /tmp folder is writable.

**Comment by rmcs2002** [comment]
Fixed it for now by changing line 55 in api.py from:

`cache='~/.todoist-sync/'):`

to:

`cache='/tmp/.todoist-sync/'):`

**Comment by PotHix** [comment]
@rmcs2002 I'm closing this one since it looks to be solved. :+1:
